#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BusUI.Resource", IsApplication=true)]

namespace BusUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Shape1 = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int addressButton = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int byAddress = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int byId = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int gridLayout1 = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int gridLayout2 = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int layout = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout1 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int sche1 = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int sche2 = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int stop1 = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int stop2 = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int stopsNear = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int submitBut = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int textDisplay = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int update = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int widgetlayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int widgetlayoutgrid = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int widgetproviderinfo = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
